### ISSUE TITLE
What are the objectives we want to accomplished before next class?

### ISSUE THREAD

**Issue by spitalnyd** [GatorCogitate/cogitate_tool#1]
Coming up with a plan and goals of objectives to get done before next week

**Comment by noorbuchi** [comment]
The tools we should research for next week are: [PyGithub](https://github.com/PyGithub/PyGithub), [PyDriller](https://github.com/ishepard/pydriller), [StreamLit](https://www.streamlit.io/), [FastAPI](https://github.com/tiangolo/fastapi)

**Comment by Cory-Wiard** [comment]
Let's make sure each group puts together a 5 minute presentation that includes a demo on the four research topics.

**Comment by liux2** [comment]
What I suggested during class by deadline is that we can choose a project management model. For example, scrum, agile, etc. I suggest we select one or modify from one, and make the schedule based on the model.

**Comment by koscinskic** [comment]
Agile seems to be a common expectation from a lot of internships I've heard of, so I'd opt for that model.

**Comment by liux2** [comment]
I agree since we are a big team. @koscinskic

**Comment by mcnultycollin** [comment]
Agile looks good to me.

**Comment by lussierc** [comment]
I think that agile would be a good option since we have a large team of over 20 people.

**Comment by gkapfham** [comment]
Hi @spitalnyd I suggest that you create a checkbox for this issue and then apply the checks to all of the tasks that were, in fact, completed by the deadline. What is the overall view, is the team on track to give demonstrations by each technology by today?

**Comment by johnsc1** [comment]
If you would like to propose objectives/deadlines moving forward, please open an issue in the project-manager-info repo !
