### ISSUE TITLE
Building and Testing Features

### ISSUE THREAD

**Issue by Cory-Wiard** [GatorCogitate/cogitate_tool#11]
This issue is used for Team Building and Testing to discuss features to create. In addition to discuss any changes, additions, or updates to the feature as we go.

**Comment by lussierc** [comment]
The three main questions are team were presented with are as follows:
1. Are there team members who contribute to source code without also adding test cases?
2. Or team members who only write test cases?
3. Are there team members who break the build or contribute to unusually high code churn?

Our team will focus on the second question to start, then use some of that work and knowledge gained to try and answer question one. Then we will circle back around to question 3.

With this, the first main feature we are planning on making is a feature to determine the number/percentage of commits that a user is committing to testing. To do this, we could look at the number of commits that a user is committing to the `/testing` directory. We could then set a threshold, of say 90% for example, to determine whether or not a user is only or almost only committing to testing.

**Comment by spitalnyd** [comment]
![Screen Shot 2020-02-11 at 21 58 17](https://user-images.githubusercontent.com/25254679/74299156-cf8f0800-4d19-11ea-943c-1717d24400cb.png)

**Comment by Cory-Wiard** [comment]
Reminder team meeting today @6 in Alden. @lussierc @spitalnyd @ABaldeosinghASC @wilsonj24 @TylerPham2000

**Comment by lussierc** [comment]
After last night's meeting, it seems that the major thing we need to figure out is the directory's of the files being modified. This will allow us to find out what commits are modifying the `tests` directory and we can then figure out who "only writes test cases".

I made a simple program yesterday using PyDriller that shows the commit author name and the files they modified.

Here is the partial output of the program with one of my old repositories:
```
COMMIT:
--- Commit Tag:  5041f2d3af9db0816a0c5ee584588def2b145436
--- Commit Author:  clussier
--- File Modified:  ResultsTable.java
--- File Modified:  RunCampaign.java
COMMIT:
--- Commit Tag:  db976075b4461925f4e4e21e882c5e597ddc1595
--- Commit Author:  clussier
--- File Modified:  writtenTaskList.JPG
COMMIT:
--- Commit Tag:  cfbb31f55c28900329076fcb015ca72542c59b90
--- Commit Author:  clussier
--- File Modified:  ResultsTable.java
COMMIT:
--- Commit Tag:  cfd5014cdfe2af40da989fcbb07f840b12748aca
--- Commit Author:  clussier
--- File Modified:  report.md
COMMIT:
--- Commit Tag:  b6766dc7a3e0db7cfb07c56af988650d989bae57
--- Commit Author:  Devin Ho
--- File Modified:  reflection.md
COMMIT:
--- Commit Tag:  b4ee2200cf50cf34973bfe4158bbf510972b0896
--- Commit Author:  Juncheng Wu
--- File Modified:  reflection.md
```

Right now, we can only see the file name being modified with our current sample program. We need to find a way to get the full file path/directory names. We should do more research and testing to see if PyDriller has this functionality.

**Comment by Cory-Wiard** [comment]
Reminder Team Meeting today @6 in alden @lussierc @spitalnyd @ABaldeosinghASC @wilsonj24 @TylerPham2000 @reid7danny

**Comment by lussierc** [comment]
I figured out how get the file paths from PyDriller by looking at the [documentation](https://pydriller.readthedocs.io/en/latest/modifications.html) on the attributes for `modified_file`. I found that we can use the attribute `new_path` to get the newest version of the file path from that commit.

Here is a sample output of our program with these updates:
```
COMMIT:
--- Commit Tag:  c5c33c7bc94313b0b5ac83817d94a24444336149
--- Commit Author:  clussier
--- Commit Date:  2018-05-01 18:43:46-04:00
--- File Modified:  src/main/java/labten/experiment/RunCampaign.java
COMMIT:
--- Commit Tag:  535ae147daf2928844784480405845b3f1c337b7
--- Commit Author:  clussier
--- Commit Date:  2018-05-02 14:09:35-04:00
--- File Modified:  src/main/java/labten/experiment/RunCampaign.java
COMMIT:
--- Commit Tag:  a49d3db4ca4a12e5801755fb09fd565c9165b0ce
--- Commit Author:  clussier
--- Commit Date:  2018-05-02 14:34:11-04:00
--- File Modified:  src/main/java/labten/experiment/Main.java
COMMIT:
--- Commit Tag:  6b89253d43d1e1966d5e0a279164c708b8a76c1c
--- Commit Author:  clussier
--- Commit Date:  2018-05-02 14:48:06-04:00
--- File Modified:  src/main/java/labten/experiment/RunCampaign.java
--- File Modified:  writing/report.md
COMMIT:
--- Commit Tag:  e2f4fc096c039fa556430d8bea98de8baff35cc9
--- Commit Author:  Devin Ho
--- Commit Date:  2018-05-02 14:50:19-04:00
--- File Modified:  src/main/java/labten/experiment/Main.java
```

**Comment by Cory-Wiard** [comment]
@lussierc Sweet! Looking forward to continue to progress this during our meeting tonight.

**Comment by wilsonj24** [comment]
@Cory-Wiard @lussierc I agree!

**Comment by Cory-Wiard** [comment]
Make sure everyone pulls before looking at the code today @lussierc @spitalnyd @ABaldeosinghASC @wilsonj24 @reid7danny @TylerPham2000

**Comment by TylerPham2000** [comment]
Some questions that we could ask tomorrow.
- What specific data would you like to see in terms of data shown in regards to test cases
- Are there any visual representations you  are specifically looking for
- What classifies as a test case

**Comment by lussierc** [comment]
Another question for the customer:

- How do we determine what the tests are? Have the user enter the path of their test cases?

**Comment by Cory-Wiard** [comment]
@lussierc @spitalnyd @wilsonj24 @TylerPham2000 @ABaldeosinghASC @reid7danny 
Additions to add to the feature still:
- Look for a specific person's commits
- Look for a specific location rather than just "tests"
Anything else?

**Comment by spitalnyd** [comment]
Make sure tomorrow we start to document the readme file and start to do code reviews o the feature already made for the most part

**Comment by ABaldeosinghASC** [comment]
I think tomorrow we should also start figuring out how we are going to integrate this with the other group's code.

**Comment by spitalnyd** [comment]
> I think tomorrow we should also start figuring out how we are going to integrate this with the other group's code.

That was an excellent point made by our colleague!!!

**Comment by Cory-Wiard** [comment]
@spitalnyd @ABaldeosinghASC Before we do that, we should finish our first feature

**Comment by spitalnyd** [comment]
> @spitalnyd @ABaldeosinghASC Before we do that, we should finish our first feature

Another excellent point made by our colleague!!!

**Comment by lussierc** [comment]
Questions for customer tomorrow:
1. Local path or online repository link?
2. How to determine who breaks the build? Is it feasible?

**Comment by spitalnyd** [comment]
It would also be a good idea to show the customer the features we have so far. So we can get feedback if needed.

**Comment by wilsonj24** [comment]
@spitalnyd I agree. For this, feedback is important

**Comment by lussierc** [comment]
Since we are moving on to working on the Web Interface, #45, I am closing this issue. We can reopen it if we have to come back and work on these features again.
