### ISSUE TITLE
Team Interactions Features

### ISSUE THREAD

**Issue by johnsc1** [GatorCogitate/cogitate_tool#13]
This issue is to track the discussion of features for the Team Interactions group.

**Comment by johnsc1** [comment]
We can also make our schedules and goals here

**Comment by cklima616** [comment]
By next week:
1. Define method to retrieve user input from terminal to define an "average" or "base" level of commits.
2. Define a similar method on Streamlit.
3. Define a method to retrieve branches in a repo.
4. Define a method to retrieve usernames from branches.
(Figure out whether PyGithub or PyDriller is more useful for 3&4.)

**Comment by johnsc1** [comment]
@cklima616 I will add those goals to a markdown document. Did we have ideas for any goals for the rest of the project?

**Comment by santacruzm** [comment]
Firstly, I want to make sure that I understand correctly our feature...the goal here is to create a feature that gathers the data collected by Individual Metrics team for comparison.

**Comment by johnsc1** [comment]
> Firstly, I want to make sure that I understand correctly our feature...the goal here is to create a feature that gathers the data collected by Individual Metrics team for comparison.

Yes, that is our goal.

**Comment by liux2** [comment]
We can research on a command-line interface that we can use, the professor suggested that after everyone left last time. We can probably consider the trade-offs and decide whether it is a good idea. Also, for now, we have two options for interface, command-line, and streamlit.  Once the API standard is determined, we can start to implement streamlit?

**Comment by liux2** [comment]
[Example of CLI for Python Projects](https://codeburst.io/building-beautiful-command-line-interfaces-with-python-26c7e1bb54df)

**Comment by johnsc1** [comment]
I added the first two weeks of the schedule to ProjectSchedule.md! We still need to add more ideas for features regarding the second questions, "Are there individuals who collaborate together too frequently or not enough?". 

Yesterday in lab when we discussed the second question, we talked about tracking if specific people worked in the same branch or on the same files often. We could track areas where 2+ people often commit to.

**Comment by liux2** [comment]
I think for the second question, we can use exhaustion to list the people by pairs. And if two people worked together in a branch, then we count one.

**Comment by johnsc1** [comment]
The ProjectSchedule.md file is tentatively complete! Please add any suggestions for edits here, preferably before midnight tonight. @liux2 I added the command-line interface research and pairing people to analyze collaboration to the plan for creating features!

**Comment by liux2** [comment]
@johnsc1 Thank you!

**Comment by johnsc1** [comment]
This issue has been transferred to #47 as our new task is to create the full Command Line Interface.
