### ISSUE TITLE
Overall Evaluation Features

### ISSUE THREAD

**Issue by koscinskic** [GatorCogitate/cogitate_tool#14]
A rough outline of this week's upcoming features and ideal deadlines:

**Features & Tasks**

* Aggregate individual commit data and assess the individual's percentage of commits both by numeric count and lines altered
* Assess quantity of opened issues, pull requests, conversation threads, and general non-commit contributions
* Analyse previous metrics to determine an individual's overall contribution score

**Schedule**

* 2 / 14 - Establish Standards for Contribution and other Metrics
* 2 / 16 - Implement Features based on Mock / External Repository Data
* 2 / 17 - Initiate Pull Requests and Address Issues

**Comment by koscinskic** [comment]
Feel free to bring up any corrections and new developments in this issue.

**Comment by koscinskic** [comment]
We can also discuss sub-issues and individual feature assignments here so we can split the work as evenly as possible.

**Comment by declanjcasey** [comment]
Hey everyone, just wanted to check in on how we're doing regarding the pull request, Thomas, Caden, and I should be done documenting metrics.py by midnight tonight.

**Comment by cassidyt2** [comment]
I'm adding my documentation now, and may begin working on some preliminary test cases too!

**Comment by declanjcasey** [comment]
Okay, I can probably help with some of the test cases during lunchtime if you need

**Comment by cassidyt2** [comment]
Sorry, just saw this! I've gotten the cases written, but when I run the test command I don't think pipenv and pytest can find the directory. I'll upload everything to github now - if you can figure it out I'd appreciate it but if not no worries!

**Comment by declanjcasey** [comment]
Okay that's perfect, I'll take a look but I have an exam at 2:30 that I should probably be studying for.

**Comment by hinckleyc** [comment]
I don't know if anyone saw the slack message but Declan, Thomas and I should get together and work on the test cases because we need them for the demo. I can meet around 7 tonight or right after class but only for a little.

**Comment by declanjcasey** [comment]
Okay, I'm free from about 4 to 6:30 but I think Thomas already finished a test case for each method, maybe we can try using coverage.py to get our code coverage up?

**Comment by koscinskic** [comment]
With teams being partially reassigned, I figured we could make use of this issue thread while it is still open. Where are we collectively on refactoring and testing our branches?
