### ISSUE TITLE
.gitignore file needed

### ISSUE THREAD

**Issue by noorbuchi** [GatorCogitate/cogitate_tool#18]
As of creating this issue tracker, there hasn't been a `.gitignore` file created to avoid committing unintended files into the repository. I think that having one is necessary to prevent unnecessary files from overcrowding the repository. I suggest that we add one similar to the standard one present in our GitHub classroom repositories.

**Comment by carmop** [comment]
I agree, I have added one to the team-interactions branch but we should have one in the main branch of the repo.

**Comment by MaddyKapfhammer** [comment]
I can work on creating a `.gitignore` file that can be merged to the master branch for future use, to ensure that each feature has a standard. Thank you for bringing this up @noorbuchi

**Comment by MaddyKapfhammer** [comment]
I have created a `.gitignore` file in the `Dependencies` branch, which when merged will be used universally for the entire software engineering project. Thank you to those who raised this issue.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer thank you for your work on the `.gitignore` file. Hopefully, a pull request will be created for the branch and the changes will be merged soon
