### ISSUE TITLE
overall-eval-analyzing-metrics

### ISSUE THREAD

**Issue by hinckleyc** [GatorCogitate/cogitate_tool#20]
Just making an issue for overall-eval-analyzing-metrics

**Comment by hinckleyc** [comment]
Declan is going to comment on standard deviation and commits calculator. Thomas is going to do total_team_score_calculator and the main method. I am going to work on the removed_calculator and the added_calculator

**Comment by hinckleyc** [comment]
How much documentation do you guys think we should put in the code? I don't know if we should document every if-statement or just comment on what the overall code does. Please let me know what you guys think is the best way to go about this.

**Comment by declanjcasey** [comment]
I kinda started documenting by whichever lines of code seemed to work together, so like I explained a whole while loop which was maybe 3 or four lines long and then commented on the next four or five lines. I would say it's up to you but aim for a comment every 4-6 lines as long as it makes sense.

**Comment by koscinskic** [comment]
To avoid red flags that reiterate the code itself, I'm only including comments concerning large general-purpose code blocks and any lines that are prone to change in the future. If we can agree to keep our variables fairly intuitive, it should cut down on the amount of necessary comments.

**Comment by hinckleyc** [comment]
I finished my comments. Thomas and Declan have you guys done the same? If so we should make a PR.

**Comment by hinckleyc** [comment]
I just made a pr.

**Comment by hinckleyc** [comment]
We have a problem with our Pipfile and Pipfile.lock. I am trying to figure it out but if you guys want to look at it and see if you know how to fix it.

**Comment by cassidyt2** [comment]
I'll look into that now. I wasn't having any trouble with it in my local repo, but there might be issues now that it's been committed to GitHub. What are the error messages you're receiving?

**Comment by hinckleyc** [comment]
I added another data set and test case.

**Comment by hinckleyc** [comment]
Make sure you pull before editing.

**Comment by declanjcasey** [comment]
Is there any other work we could currently be completing? I'm not really sure how much refactoring there is to do and both @hinckleyc and I felt we could be doing more work currently

**Comment by hinckleyc** [comment]
I worked on fixing Travis ci errors for the master branch because I had extra time to work on it. But if there is work for our part of the project just let me and @declanjcasey and we will start working on it.

**Comment by cassidyt2** [comment]
If anyone has any ideas for additional metrics we can include, please add them here! I was thinking perhaps an average of commits per document edited? Like (# Commits/documents edited)

**Comment by hinckleyc** [comment]
So since we are not using our program should we delete it?
