### ISSUE TITLE
Add documentation to metrics.py

### ISSUE THREAD

**Issue by cassidyt2** [GatorCogitate/cogitate_tool#22]
My metrics.py document  does not have documentation. I will start adding documentation later today, and if anyone else wants to help and can understand the code go ahead.

**Comment by schultzh** [comment]
I would not make documentation a priority at this time. Everything else in your branch looks good. We will be creating documentation for the tool as a whole later on. For these reasons, I am going to close this issue. Thanks for all your hard work!
