### ISSUE TITLE
Testing Guidelines

### ISSUE THREAD

**Issue by MaddyKapfhammer** [GatorCogitate/cogitate_tool#24]
As we continue working on completing this project, it would probably be beneficial to determine some guidelines for testing, as that should be one of our next steps. Perhaps we should discuss what level of coverage we would like to obtain for all of our tests (is 100% attainable)? and how our test suites should be organized? Does anyone have any input?

**Comment by johnsc1** [comment]
I think we should strive to achieve the highest coverage possible but allow for a slight margin of error. I think about 97% is acceptable if that is the best we can achieve.

**Comment by bagashvilit** [comment]
I think that for now, we can start with unit testing, and then implement integration/systems testing. However, I support other ways too. 
I was also wondering, as for now, is it required to have a test suite to get the pull request merged?

**Comment by MaddyKapfhammer** [comment]
@bagashvilit in the schedule that the project managers created for last week's lab session, we did include that you should have tests along with creating your PR by tonight at 11:59pm. These do not need to be extensive tests (as we will most likely add to them later) but just a few to ensure correctness in your code.

**Comment by bagashvilit** [comment]
@MaddyKapfhammer Thank you for the clarification

**Comment by schultzh** [comment]
I think 100% coverage is possible, but allowing some leeway may be helpful in mitigating the
daunting task of code coverage. 

I think in terms of designing a test suite we need to be able to create an organization separating tests into various files while also ensuring there are not repeat tests from multiple teams.

**Comment by bagashvilit** [comment]
So for tomorrow's demonstration should we create our own test files in our branches?

**Comment by MaddyKapfhammer** [comment]
@bagashvilit yes, if you could create your own test files in your branches that would be appreciated. They do not need to be extensive, just simple like the ones that we have been working on for our practical assignments.

**Comment by koscinskic** [comment]
Given the somewhat hasty nature of our organization, I don't believe we should ultimately be aiming for perfect code coverage. Having said, what we can achieve in our final product will become more apparent over time, but do we want to set a short-term goal for the time being? We could also integrate a Travis check that requires a certain amount of code coverage for the build to pass.

**Comment by gkapfham** [comment]
Hi! At the start, I suggest that we aim to have tests for every module of the program and for every function in the program. After that, we can aim to create "stronger" test cases that cover all of the statements of the program. Finally, we can focus on trying to create "even stronger" tests that cover all of the branches of the program. Let me know if you have any further ideas! Finally @koscinskic, if we have a "hasty nature for our organization", then I think that we should fix that!

**Comment by lussierc** [comment]
I agree with the thoughts that while 100% code coverage is possible, that a little bit of leeway should be allowed, maybe in the area of 97%. It is important to consider that there are some lines that are hard to test, such as lines of code containing function calls. We should aim to continuously improve our test suite's coverage as we strive for 100% coverage.

**Comment by koscinskic** [comment]
Moving forward with the project, one way to effectively address code coverage as well as rectifying the hasty organization I mentioned previously would be to partially dissolve the old teams and create new groups dedicated to feature integration and test cases on the integration. I mentioned the concept of poor organization due to the fact that our feature-focused team structure has resulted in multiple teams requiring implementations of the same code that would have been otherwise avoided had integration been a concept brought up far earlier in the project's development cycle. This is merely a proposition, but I do believe restructuring teams may help with integration and refactoring, which would in turn help to push code coverage up.

**Comment by MaddyKapfhammer** [comment]
@koscinskic I think that creating new teams could be beneficial, and maybe something that the project managers should discuss in more detail in person. Perhaps it would be helpful to not completely dissolve our teams, but rather just reassign them to work on different tasks, as we already have familiarity working with each other, and slack groups etc. This could prevent even more confusion within our project, and also allow us to be more successful in creating our tool.

**Comment by koscinskic** [comment]
That could definitely work. Perhaps we could have a joint meeting with software architecture to reassign team members?

**Comment by MaddyKapfhammer** [comment]
@koscinskic I think that this is something that we should discuss further in person tomorrow at our project managers meeting and go from there, and possibly meet with software architecture if we deem it necessary.

**Comment by MaddyKapfhammer** [comment]
This issue has not been utilized in a few days, and I believe that individuals are currently on the same page with writing test cases and code coverage. We are striving for 100% code coverage of tests with each teams' feature that is developed. With this understanding, I am going to close this issue; it can be reopened if necessary.
