### ISSUE TITLE
Test suite for overall metrics

### ISSUE THREAD

**Issue by cassidyt2** [GatorCogitate/cogitate_tool#28]
- I have written the test cases, but when I run the test command the virtual environment can't find my cases. If someone can help me with this I'd appreciate it!

**Comment by declanjcasey** [comment]
Just to add on, this is the error message I get in my terminal:

```
Traceback (most recent call last):
  File "test_metrics/metrics_tester.py", line 3, in <module>
    from calculate_metrics import metrics
ModuleNotFoundError: No module named 'calculate_metrics'
```

**Comment by gkapfham** [comment]
Hi @declanjcasey and @cassidyt2 I suggest that, at least for now, we think of ways to avoid using an underscore in the name of our modules. For instance, could we call this module `metrics`?

**Comment by cassidyt2** [comment]
Yes, I will rename those files now Professor!

**Comment by MaddyKapfhammer** [comment]
@cassidyt2 @declanjcasey are you both still having issues with running test commands?

**Comment by MaddyKapfhammer** [comment]
It seems that this issue has been solved, and thus I will close it for now. If any other testing issues arise please reopen this issue or create a new one!
