### ISSUE TITLE
Adjusting Repository Permissions

### ISSUE THREAD

**Issue by koscinskic** [GatorCogitate/cogitate_tool#29]
Seeing as we're entering the stage of development where we're going to be opening and reviewing a lot of pull requests, we should configure the permissions to require a certain number of reviewers as well as restrict who has permission to execute the merge itself

**Comment by MaddyKapfhammer** [comment]
I think that this is a great idea. Perhaps we could announce these requirements tomorrow during our annoucements section at the beginning of lab (considering that we devise these requirements tonight). I think that each of the project managers should be assigned as reviewers, and at least one TL and maybe some members of the team. Perhaps we should require approval from two project managers, one team member and one TL before merging? Does anyone else have any input?

**Comment by johnsc1** [comment]
@MaddyKapfhammer I agree with your idea for who should review and who should approve!

**Comment by schultzh** [comment]
Sounds good to me!

**Comment by carmop** [comment]
Aren't the architects technically supposed to ensure the code is in the right format and the right standard? If so I believe one of the members of the software architects should also be included, maybe the one that belongs to the group originally or maybe just any of the four.

**Comment by MaddyKapfhammer** [comment]
@carmop I think this is a great point! Maybe it would make the most sense to assign the architect from an individual's team to their pull request, and then we can add a software architects' review to the list of review requirements.

**Comment by MaddyKapfhammer** [comment]
I have created a file in the `project_managers_info` repository named `Guidelines.md` which states the requirements for reviews as approval (before merging) from:
- 1 project manager
- 1 TL
- The software architect from your team 
- 1 other team member (not architect or manager)

I also changed the requirements for PR approval to require 4 approvals before a PR can be merged for our `cogitate_tool`. If there are any requirements to change or add this can be done in the `Guidelines.md` file.
