### ISSUE TITLE
Pydriller

### ISSUE THREAD

**Issue by WonjoonC** [GatorCogitate/cogitate_tool#3]
This opens the floor to discuss things about Pydriller.

**Comment by mcnultycollin** [comment]
Do you guys need help with anything in preparation for tomorrow?

**Comment by hinckleyc** [comment]
No. We are making the demo and everything should be done before the lab starts at 2:30. Thank you for offering though.

**Comment by guzmanr04** [comment]
Yeah, we should be fine for the most part. We will let you know if we need some help.

**Comment by declanjcasey** [comment]
So the plan at the moment is to meet at 11 tomorrow in the CC to work on the actual code we need, is everyone okay with that?

**Comment by TylerPham2000** [comment]
I'm able to meet at 11 tomorrow.

**Comment by guzmanr04** [comment]
I have some classes tomorrow morning and will be arriving a bit late.

**Comment by hinckleyc** [comment]
I am going to be there.

**Comment by declanjcasey** [comment]
Hey Megan, what features did you end up working on last night?

**Comment by gkapfham** [comment]
Hi @WonjoonC can you please update as to whether or not you will be able to give a demonstration about the Pydriller tool? Thanks!

**Comment by WonjoonC** [comment]
Yes, I have class conflict, but I can try to get out of my previous class earlier. If our team could demonstrate last I should be able to be there. I was preoccupied this morning, but I will be there to work with them soon before 1:30.

**Comment by munzekm** [comment]
@declanjcasey I added the important features about Pydriller and how we can use it toward our project. I added this in our README file.
