### ISSUE TITLE
Missing Templates For Issues And PRs

### ISSUE THREAD

**Issue by Lancasterwu** [GatorCogitate/cogitate_tool#38]
This Issue is a bad example of raising issues. :hurtrealbad: :hurtrealbad: :hurtrealbad: :hurtrealbad:

Following links can be helpful for contributing this project:

[Creating a pull request template for your repository](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

[Configuring issue templates for your repository](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by carmop** [comment]
Ah, classic Lancaster

**Comment by MaddyKapfhammer** [comment]
@Lancasterwu thank you for raising this issue to help us with our formatting of issues and PRs! I have added these links to the `Guidelines.md` file in the `project_managers_info` repository. Here is the [link](https://github.com/GatorCogitate/project_manager_info/blob/master/Guidelines.md). The project managers will also discuss creating guidelines for these areas through GitHub.
