### ISSUE TITLE
FastAPI Research

### ISSUE THREAD

**Issue by stephensonc** [GatorCogitate/cogitate_tool#4]
This group is responsible for researching tools of the same type as FastAPI and determining:
- If FastAPI is the best tool for this purpose
- How to use the tool we deem best for the purpose

**Comment by mcnultycollin** [comment]
Looks like creating a demo API will be pretty easy using the tutorial on the Github page. We just need to figure out what kind of methods / libraries or whatever we will be demoing. 
https://github.com/tiangolo/fastapi

**Comment by noorbuchi** [comment]
In addition to the tutorial on the GitHub page, there is this in-depth [tutorial](https://fastapi.tiangolo.com/tutorial/) on how to use the tool. It might be worth checking out to understand it more.

**Comment by noorbuchi** [comment]
Hi everyone, I  just added a commit to our branch that combines PyGithub and FastAPI. I realize that some things are missing and could be improved. Please check the readme file before changing anything. Feedback would be greatly appreciated!

**Comment by noorbuchi** [comment]
Hi everyone. I just updated the branch with a new feature. There are some issues with the current build but I'm not sure how to fix them. If you get a chance, please check it out and help me in fixing the issue with the `branches_list` function. Thank you!

**Comment by mcnultycollin** [comment]
I am going to attempt to switch the name to main.py and see if that fixes the issue.

**Comment by mcnultycollin** [comment]
Looks like the name is not a factor. Here is the current error with running this program:
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12772]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/collin/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/collin/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/collin/.local/share/virtualenvs/cogitate_tool-kFhXErz5/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 2, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github'
```

**Comment by mcnultycollin** [comment]
Update: Switching to this simple code
```
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}
``` 
yielded a successful server. This means that the error must be within our main.py program.

**Comment by mcnultycollin** [comment]
Deleted all but the first method and still got the same error, so it involves this method:
@app.get("/create_user")
def create_user(user_token):
    global current_user_token
    current_user_token = user_token
    global current_user_account
    current_user_account = Github(user_token)
    user = current_user_account.get_user()
    statement = user.login + " created successfully!"
    return statement

**Comment by mcnultycollin** [comment]
Update: we were missing pyGithub in our Pipfile.

**Comment by noorbuchi** [comment]
UPDATE: All past issues have been solved with the latest commit! README file has also been updated to show more comprehensive and clear instructions. Unless someone has any questions or suggestions, we can close this issue tracker. Thanks everyone!

**Comment by koscinskic** [comment]
I would think we should keep the research branches open for future consultation and reference between teams. That way, if anyone makes any breakthroughs or finds a particularly useful feature, we can more easily integrate that improvement across Cogitate features.

**Comment by noorbuchi** [comment]
ISSUE: Even though everything is working when running the program using the FastAPI method or by simply running `python demo.py` there is a current small issue with this branch when running the python file using  `pipenv run python demo.py` command. Doing so will result in `ModuleNotFoundError: No module named 'GitHub'` error regarding the import GitHub statement at the beginning of the file. It would be great if we can add a quick fix to this issue before our demo tomorrow. Thank you!

**Comment by stephensonc** [comment]
I can take a look at the module error.

**Comment by stephensonc** [comment]
@noorbuchi It looks like you need to do a `pipenv install --dev` before attempting to use the pipenv run command. I just tested that procedure and it imports correctly. I have not created a github api token yet in order to test the rest of the program, but I believe you had stated that the program functions properly.

**Comment by noorbuchi** [comment]
@stephensonc that is correct, you will need to run the install command before attempting to run the program. However, even after running the install command, using the `pipenv run demo.py` command will not correctly run the program. You can still run it without the fastAPI in your local python version using `python demo.py`. I'm not sure this clarifies things, please let me know. Thanks!

**Comment by stephensonc** [comment]
I just typed in both 'pipenv run python demo.py' and 'pipenv run python3 demo.py' and both ran error-free on my machine

**Comment by stephensonc** [comment]
I think that it might be a good idea to have the demo program print the functions it is calling at the time it calls them

**Comment by cassidyt2** [comment]
I will work on adding the necessary print statements to give the other teams clarity as to what is happening in our program when we give the demo

**Comment by mcnultycollin** [comment]
Running a main method requires that the program execute in the terminal rather than on the localhost.

**Comment by noorbuchi** [comment]
@mcnultycollin having the main method will not, in fact, cause that issue. It will still allow you to run the localhost as long as you complete the terminal prompts first. You can also choose not to run the terminal prompts at all when asked.

**Comment by cassidyt2** [comment]
Because I don't have editor privileges I will add the documentation and explanatory print statements for tomorrow's demo, and provide my changes to team members with the necessary privileges using slack.

**Comment by cassidyt2** [comment]
I have added documentation to the 'def get_repo_list():' and 'def create_user(user_token):' methods as well as the print statements in 'def main_method():' but have not yet received editing privileges, so someone else will commit and push these changes for me

**Comment by gkapfham** [comment]
Hi @cassidyt2 and @stephensonc could I trouble you to correctly use the Markdown syntax for the source code segments so that it is easy for everyone to read your comments? Thanks!

**Comment by johnsc1** [comment]
I pushed the commit for @cassidyt2 with the print statements and documentation he completed, in addition to the documentation I added to 'def get_repo_info( )' and print statements to a few other methods

**Comment by johnsc1** [comment]
I committed the documentation @cassidyt2 completed, along with the documentation I added to 'get_repo_info( )' and print statements in several other methods

**Comment by johnsc1** [comment]
I closed the issue by accident so I am reopening it. I apologize for any confusion.

**Comment by johnsc1** [comment]
I closed the issue by accident. I apologize for any confusion.

**Comment by johnsc1** [comment]
I reformatted the comments in demo.py. I can make further changes to them if necessary.
