### ISSUE TITLE
Scoring/individual-metrics-and-overall-evaluation

### ISSUE THREAD

**Issue by MaddyKapfhammer** [GatorCogitate/cogitate_tool#48]
This will allow us to determine the metrics that both an individual and a team will be evaluated. The `Individual Metrics` and `Overall Evaluation` teams will work together to determine these metrics to ensure that we are looking at similar data for both the individual and the project/team as a whole.

**Comment by cassidyt2** [comment]
In terms of categories both our groups are looking at, I think the general consensus for broad categories I heard was:
- commits
- additions
- removals
- something to do with issues (if we end up using pygithub to access issues info)
- file types edited

We can add more in the future, but this is a preliminary action plan.

**Comment by cassidyt2** [comment]
An idea for individual metrics using an averaged ranking system:
using the format of: username, commits, addtions, removals, ratio of commits to additions
a sample list of rankings with 1 being, for instance, the person with the most commits, and 5 being the person with the least a sample list of the first two people in a team of 5 could look like:

johnSmith, 1, 5, 3, 4
janeDoe, 3, 4, 2, 5

johnSmith's average = 3.25
janeDoe's average = 3.5 

so Jane would receive a higher score than John. However, I am unsure of the best way to develop a score based on this, or how ties would factor in. It could also be a good idea to decide a persons ranking based on a window. Aka, it could be a good idea to give EVERYONE in the window of 2.5+ Standard Deviations the highest ranking (this is actually a good idea, because right now John is failing despite being above the middle possible rankings in a team of 5). This rewards people for high performance, but also provides a standardized framework for determining what constitutes high performance.

**Comment by MaddyKapfhammer** [comment]
I think that for now the easiest course of action is to determine the percentage of contribution for each individual, compared to the total from the entire branch. This gives the user and indication of how much code they wrote, or contributed in comparison to others without having to deal with a scoring system that is not easily developed, as then that is ranking individuals, which seems more like an overall evaluation. We can then determine an average percentage, for overall contribution for all of the categories. @bagashvilit and I even discussed implementing a feature that allows a user to determine the weight for each category, according to what they are looking for, which will then be used in determining the overall contribution. Our ideas are documented with TODO statements in the `individual-metrics-lines` branch in the `individual_scoring.py` file.

**Comment by bagashvilit** [comment]
@MaddyKapfhammer Just to be clear are we still doing the rankings?

**Comment by bagashvilit** [comment]
@MaddyKapfhammer Thank you for adding the fake data to our file, I thought that we were going to use a dictionary and also @noorbuchi ' s team will most likely store the data as a dictionary. When I checked the type with the following line of code `print(type(github_data))`,  it showed `<class 'list'>` in my terminal window. I was thinking to switch it to a dictionary but first I want to make sure how `values` will be stored in a dictionary. I think our fake data would depend on that and so will our algorithm for sorting it. Also please see @noorbuchi 's comment in Slack and issue #35

**Comment by noorbuchi** [comment]
@bagashvilit @MaddyKapfhammer I just posted an update on issue #12 regarding the data structure choice. Please check it out and let me know what you think. I think that @MaddyKapfhammer makes a great point about a percentage of contribution metric and I think that it would fit well in our data structure. Additionally, we can work with the overall evaluation team to provide any needed processed data for specific users into our dictionary. Any feedback would be appreciated.

**Comment by bagashvilit** [comment]
@MaddyKapfhammer @WonjoonC I added some code for scoring. currently, this program calculates the percentage of individual contribution (individual * 100/ branch) for each category: `COMMITS`, `ADDED`, `REMOVED` separately. Please review it whenever possible. If it works then we need to figure out what to do with this data to get the final score.

**Comment by WonjoonC** [comment]
@bagashvilit @MaddyKapfhammer Good work with the new individual metrics evaluation. From what I am understanding is that we are finding the percentage for each individual metric from the total regarding commits and lines added/removed? I think that the ranking system as @cassidyt2 suggested would be a good indication of individual success/performance. As for implementing these calculations for the TODO's statements, are we directly adding them into the ```individual_scoring.py``` file?

**Comment by koscinskic** [comment]
Looking at everything that has been done so far, the tool appears to be in a good place for assessing all of the data and expectations above, but how close are we / how capable is the tool when it comes to answering the original questions posed by the customer? (e.g. how are we factoring commits that don't contain test cases / how are we measuring frequency of collaboration / etc.)

**Comment by MaddyKapfhammer** [comment]
@bagashvilit @WonjoonC thank you for all your work on these features so far! Yes, we are adding these calculations//features directly to the `individual_score.py` file! I will review the already implemented features, and also implement the features that I was assigned to tonight, and tomorrow. 

@koscinskic currently, we are focusing on more simple metrics to deal with contributions. It is not simple to design a metrics system that will deal with all of the questions posed by the customer, as it requires to much subjective data, so we will be focusing on more raw data. As we are a part of the individual metrics team, we will not be assessing collaboration or testing, but rather commits, lines added/deleted and other more simple data.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer @bagashvilit Considering that the refactoring portion of our original is almost complete, I think we should start working together on how the individual metrics we stored will be incorporated into the overall evaluation. Let us know what you think about this moving forward and how we can help you integrate the two aspects of the tool.

**Comment by MaddyKapfhammer** [comment]
@noorbuchi I agree that we should start working together to determine how individual metrics and overall evaluation will fit together. Currently, we are using fake data for our calculations, perhaps tomorrow in lab we can discuss how to implement our features with real data that is mined, together. This could be very beneficial in completing our features as soon as possible.

**Comment by MaddyKapfhammer** [comment]
@bagashvilit it seems like the code that you have written will provide the percentage of contribution for any metric that is added into the fake data dictionary. I think that tomorrow in lab we will be able to focus on converting this fake data to using real data, and then our features will be able to be completed.

**Comment by bagashvilit** [comment]
Individual metrics and team evaluation features were merged into the master branch, therefore I am closing this issue.
