### ISSUE TITLE
Command Line Interface - Customer Questions 

### ISSUE THREAD

**Issue by johnsc1** [GatorCogitate/cogitate_tool#49]
This issue is for the Command Line Interface Team (formerly Team Interactions) to ask the customer questions regarding the CLI. All other information for the Command Line Interface Team can be found in Issue #47 .

**Comment by gkapfham** [comment]
Can someone please comment on the status of this issue? Thanks!!

**Comment by hodevin** [comment]
There are no more questions that need to be addressed to the customer at this stage. It seems there is no longer a need for this issue. @gkapfham
