### ISSUE TITLE
Research Team: Streamlit  

### ISSUE THREAD

**Issue by spitalnyd** [GatorCogitate/cogitate_tool#5]
Researching Streamlit and presenting it by the next class

**Comment by spitalnyd** [comment]
Plan to meet at 4:15 to go over our demo

**Comment by hodevin** [comment]
I second this @spitalnyd

**Comment by lussierc** [comment]
Sounds good @spitalnyd.

I was thinking we just try to make a simple interface using Streamlit that possibly displays some simple data that Cogitate would actually display when the tool is completed. If you install Streamlit and run the “streamlit hello” command for Streamlit's hello world example, then look at the plotting demo, I feel we could easily reference some of the plotting demo code and use sample data to relate it to Cogitate/GitHub. For example, print out sample commit data from a repository in a plot similar to that from the demo.

**Comment by lussierc** [comment]
For reference, [here is the Streamlit documentation](https://docs.streamlit.io) which contains the info on how to install and get started with Streamlit. It also contains information about running the Hello World example I mentioned in my last comment.

**Comment by spitalnyd** [comment]
Plan:
Explain what Streamlit does?
Do basic demo streamlit?
Do a demo of streamlit related to our project?
explain how streamlit will be develop in our project

**Comment by Cory-Wiard** [comment]
Slide 1: Cory Wiard
Slide 2: Xingbang Liu
Slide 3: Devin H.
Slide 4:  Anthony
Slide 5: Devin and Jordan
Demo: Christian and Danny

**Comment by liux2** [comment]
https://docs.google.com/presentation/d/1A93gvlvMzHBLq_91Lb4QW_gussGtwzs2onTp4om3CYg/edit?usp=sharing

**Comment by ABaldeosinghASC** [comment]
I'm ready for my part of the slides tomorrow.

**Comment by hodevin** [comment]
Thank you for cooperating team.

**Comment by gkapfham** [comment]
Hi @lussierc when you are giving the demonstration, please try to do your best to ensure that you stress how it is possible to apply this tool to the creation of the tool we are building! Thanks!

**Comment by gkapfham** [comment]
Hi @Cory-Wiard when you are referencing specific people, could I trouble you to please "at mention" them so that this will show up as a notification and they will know to participate in the discussion? Thanks!

**Comment by lussierc** [comment]
@gkapfham, thanks for the insights! I will do my best to emphasize how Streamlit could be used as we continue to develop Cogitate.

**Comment by Cory-Wiard** [comment]
@gkapfham, I just updated the comment in order to fulfill that requirement and will be sure to do so every time in the future.

**Comment by spitalnyd** [comment]
This topic has been fully researched and will be close
