### ISSUE TITLE
Contemplate the removal of the python 3.6.8 builds in Travis CI

### ISSUE THREAD

**Issue by stephensonc** [GatorCogitate/cogitate_tool#53]
As it is right now, it is currently taking hours to build one commit/branch because it takes at minimum six(6) minutes to build each time. When all of us are working in one repository, this results in obscenely long queue times before we can see if our build passes.

Removing half of the builds would help to speed up the queue times at least slightly (I understand that Travis tries to build things concurrently) if not significantly. I also think that Travis would be able to run multiple commit builds at a time, because it only needs to do half of the builds per commit.

Another potential solution to long queue times with/without reducing the number of builds per commit would be to have each team create a fork and push changes on those instead of on the base repository.

**Comment by carmop** [comment]
I completely agree, if we want to expand the number of builds to test for the different python versions ans OSs we can do that later in the project. Right now the travis time is a barrier that doesn't let us move forward w the project.

**Comment by johnsc1** [comment]
Forking repositories is a skill we are required to work with according to our assessment sheet for each week of the lab, so I think forking the repository would be a good solution!

**Comment by schultzh** [comment]
I will be adding code coverage reports to the travis build tonight and can also reduce the number of test builds to two in that PR. Thanks for bringing this up!
