### ISSUE TITLE
Individual Metrics Code Clarity - README Improvement

### ISSUE THREAD

**Issue by mcnultycollin** [GatorCogitate/cogitate_tool#59]
Hello, I am having difficulty understanding how the code in Individual Metrics works, and how to run the code to see that it is working correctly. I strongly believe that steps need to be taken to improve the ReadMe file and provide a more in depth explanation of how the files interact with one another. This would essentially be an API.

Currently following the instructions to run in the Readme gives this error
```
  File "print_table.py", line 48, in <module>
    DATA = individual_metrics.calculate_individual_metrics(FILE_NAME)
  File "/home/collin/203/cogitate_tool/src/individual_metrics.py", line 61, in calculate_individual_metrics
    current_data = json_handler.get_dict_from_json_file(json_file_name)
  File "/home/collin/203/cogitate_tool/src/json_handler.py", line 14, in get_dict_from_json_file
    with open(os.path.join(data_path, json_name + ".json"), "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './data/../.json'

```
Figuring how to run the program correctly seems like a great first step. Can some of the contributors of individual_metrics, and print_table specifically explain what their program does, how it works, what programs it interacts with, and how to run the program with greater specificity? This would empower more meaningful contributions to the project moving forward.

**Comment by Jordan-A** [comment]
Hi! I agree that it would be helpful to everyone if we expanded the readme file of our repo branch. I remember seeing the program working earlier today. What was your input?

**Comment by munzekm** [comment]
Hi, I agree that this is a great idea to do! I have also tried running and reproduced the same error as Collin. We should figure out if this is a problem for everyone or just on our end.

**Comment by noorbuchi** [comment]
With our latest changes to the files mentioned above, we changed how the program is interacted with in terms of input and output. While the old steps and the new steps are very similar, an explanation is needed in the Readme file. We will work on resolving this issue today in our lab session be providing clear steps on how to run the program.

**Comment by WonjoonC** [comment]
I agree with @mcnultycollin as well. In further note, I believe it would be a good idea to document in the ```README``` file to more in depth so that the user and other developers can fully understand the workings of our code.

**Comment by MaddyKapfhammer** [comment]
I agree that the code is slightly difficult to understand, documentation will definitely help, but a code review/explanation during our lab session may also be helpful so that all of our team is on the right page. I agree that we need to document all of our features, and the tool as a whole. I have started doing this in a `README` file for the entire tool, in the `Documentation` branch. I am hoping to have this almost fully completed by Thursday afternnon.

**Comment by mcnultycollin** [comment]
thank you all for the support. Look forward to our meeting today.

**Comment by Jordan-A** [comment]
@mcnultycollin In our merged pull request we just updated the `README.md` file. If possible, it would be nice to get your feedback on the changes made! 💯

**Comment by MaddyKapfhammer** [comment]
It seems that we have accomplished what was necessary for this issue, and have a more descriptive feature that was merged to `master`! Great work everyone! For this reason, I am going to close this issue, if necessary please feel free to reopen it.
