### ISSUE TITLE
Add issues metric to the calculateMetrics module in branch overall-eval-analyzing-metrics

### ISSUE THREAD

**Issue by cassidyt2** [GatorCogitate/cogitate_tool#68]
Create a new metric that incorporates (comments_on_issues_assigned/comments_on_issues_not_assigned), and provides a score/5 based in the same manner as the other metrics

Step by step: 
- Add to sample data two more values: 
   - Number of issues assigned to
   - Number of total comments
- Calculate the standard deviation of the team's standard deviation for comments_on_issues_assigned/comments_on_issues_not_assigned
- Calculate a score for each user based on how far away they were from the mean
- Average each user's score to get the team's score

**Comment by declanjcasey** [comment]
I'll be working on this today after my lab at 4:20, I don't think it should take too long but others are welcome to come and work

**Comment by koscinskic** [comment]
@declanjcasey You should probably directly insert those lines into the block of code for retrieve_issues in data_collection and add 2 extra keys in the .json to accommodate for such additions.

**Comment by declanjcasey** [comment]
Okay, I didn't end up working on it yesterday and I may need help regarding the keys in .json as I haven't worked with json too much before, but I'll keep looking into it.

**Comment by declanjcasey** [comment]
Also I don't see data_collection in my repo after pulling, does that have to do with merging the master back into your branches to get the latest updates, like @noorbuchi mentioned in slack yesterday?

**Comment by hinckleyc** [comment]
The 6th one is pointless u can delete it

**Comment by hinckleyc** [comment]
@declanjcasey and I finished the first step and will complete the rest of the steps tomorrow during our classroom session.

**Comment by noorbuchi** [comment]
Hi everyone! please check the `individual-metrics-lines` branch. Some of the issue and PR counting features have been added. However, there is still more analytics that could be done with them and more information about them that could be added. Please let me know what things you're considering adding so we can coordinate. Thank you!
