### ISSUE TITLE
Dependency List / Demo Branch

### ISSUE THREAD

**Issue by koscinskic** [GatorCogitate/cogitate_tool#7]
In preparation for tomorrow's demos, we should get a list of dependencies together and create a few unified files(e.g. travis.yml, pipfile, etc.) that accommodate all of these dependencies.

**Comment by noorbuchi** [comment]
hi @koscinskic ! the dev packages used for our group, FastAPI are the following
```
fastapi = "*"
uvicorn = "*"
black = "*"
pylint = "*"
flake8 = "*"
pydocstyle = "*"
pytest = "*"
PyGithub = "*"
```
However, we did not use the pytest, this is simply for future use of test suites

**Comment by MaddyKapfhammer** [comment]
@noorbuchi Thank you for adding the dev packages for FastAPI! @koscinskic perhaps we could put this on the schedule for the lab session tomorrow? That way we can break this up into responsibilities for each team to work on and hopefully will be able to make a comprehensive list to then create the unified files.

**Comment by koscinskic** [comment]
That would be a good candidate for the schedule, but should we push demos back towards the middle or end of the lab to accommodate that? The integration of all of the demos into master was why this was brought up in the first place.

**Comment by lussierc** [comment]
> That would be a good candidate for the schedule, but should we push demos back towards the middle or end of the lab to accommodate that? The integration of all of the demos into master was why this was brought up in the first place.

This is probably a good idea. It would give teams enough time to organize themselves for their demos and also add the necessary packages. My research team (Streamlit) has a few different packages we will need in addition to the linting/testing ones that were presented above:
```
streamlit = "*"
numpy = "*"
pandas = "*"
```

**Comment by gkapfham** [comment]
Hi! Please note that, sometime in the near future, our team will also need to setup a Travis CI build system for the project. This build system should be able to install all of the Python-related dependencies for the project and then run the main program and its test suites, along with performing linting and other tasks.

**Comment by MaddyKapfhammer** [comment]
I will add time for researching and listing dependencies at the beginning of the schedule. While tool teams are working on this, and preparing for their short demos, the project managers can work on starting to create a Travis CI build system for the project. Thank you for these recommendations @koscinskic @lussierc @gkapfham!

**Comment by gkapfham** [comment]
Thanks @MaddyKapfhammer, your help is appreciated.

**Comment by johnsc1** [comment]
@WonjoonC @santacruzm Could you please comment a list of your team's tools/dependencies? There will be a few minutes at the beginning of lab to do this, but it can also be done before lab.

**Comment by santacruzm** [comment]
@johnsc1 It is my understanding that the dev packages for PyGitHub are similar to what Noor provided earlier. This is considering that [PyGithub](https://pygithub.readthedocs.io/en/latest/introduction.html) is a Python library to use the [Github API v3](https://developer.github.com/v3/).

**Comment by MaddyKapfhammer** [comment]
@santacruzm Thank you very much for providing this information for us! We will add it to our project wide files, as we create them!

**Comment by MaddyKapfhammer** [comment]
All of the dependencies have been added to a unified `Pipfile` in the 'Dependencies' branch along with `Pipfile.lock` and `.gitignore` files. Thank you to everyone who listed the dependencies necessary for this software engineering project.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer While I was running my test cases, I noticed that we are missing the `pytest-cov` dependency needed to calculate the coverage of the test cases. I am reopening this issue to request a change to our current dependency list in the master branch Pipfile and add `pytest-cov`. Please let me know if this is not the appropriate issue tracker to bring this up, in that case, I will raise a different one to discuss `pytest-cov` specifically.

**Comment by noorbuchi** [comment]
I would also like to suggest that we add the cover script file that allows the Pytest plugin to run using the simple command `pipenv run cover`

**Comment by MaddyKapfhammer** [comment]
@noorbuchi thank you for bringing up this issue. I will work on updating dependencies to deal with these problems. I also will be working on adding the dependencies from each branch's `Pipfile` and `Pipfile.lock` so that these can be removed before merging to the `master` branch.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer thank you for updating the dependencies. Can you please add `PrettyTable` to the list as well since we used it in the individual metrics branch to print out organized tables.

**Comment by MaddyKapfhammer** [comment]
@noorbuchi yes! I can add `PrettyTable` to the dependencies! Thank you for letting me know about this addition, if you have any others I can add those as well.

**Comment by MaddyKapfhammer** [comment]
I have added the `pytest-cov` and `PrettyTable` dependencies to the `Pipfile` and updated the `Pipfile.lock` in a new branch called `New_dependencies`. I will leave this branch open, to continue updating it as necessary.

**Comment by MaddyKapfhammer** [comment]
I have also updated the dependencies in the `New_dependencies` branch to include everything in current branches. I believe that before merging features to `master` each branch should remove their `Pipfile` and `Pipfile.lock` to prevent merge conflicts. Does anyone have any opinions on this idea?

**Comment by schultzh** [comment]
@MaddyKapfhammer I think that is a very effective course of action to deal potential merge conflicts for the many piffles currently being used.

**Comment by lussierc** [comment]
@MaddyKapfhammer I agree with this idea. Teams should communicate their needed dependencies and remove their personal `Pipfiles` in order to avoid conflicts.

**Comment by lussierc** [comment]
@MaddyKapfhammer Would you be able to add the dependencies `devml` and `gstats` to the Pipfile? These, specifically the `devml` dependency, offer the easy calculation of code churn in a repository, which will be very helpful when it comes to implementing my group's third feature.

**Comment by MaddyKapfhammer** [comment]
@lussierc I can add these dependencies tonight! Thank you for letting me know that you need them!

**Comment by lussierc** [comment]
Thank you, @MaddyKapfhammer!

**Comment by MaddyKapfhammer** [comment]
With the `New_dependencies` branch being merged to the `master` branch, I am now going to close this issue, it can be reopened if necessary. In order to update each teams' dependencies `master` needs to be merged to each existing branch. This can be done with the command `git merge master`.
