### ISSUE TITLE
Multiple 'main' methods

### ISSUE THREAD

**Issue by cklima616** [GatorCogitate/cogitate_tool#78]
Hello all, 
I have noticed that multiple main methods are declared in various branches, and I would like to point out that if there's more than one, the program won't know which to run! I know in the Pipeline example provided they had one, but we are taking a more modular approach that includes multiple classes. This means the method that calls functions marked `if __name__ == "__main__"` should be in the cogitate.py file, coded by the CLI group.

If anyone has any questions or concerns about this, feel free to respond in this issue. But this is very important to keep in mind when reviewing pull requests.

**Comment by Jordan-A** [comment]
Great points @cklima616! I think that if we made these changes it would make our code better adhere to the pipeline programming style.  I think it would also be great to hear from someone in the command line interface group.

**Comment by cklima616** [comment]
@Jordan-A I'm in the CLI group! If anyone any questions come by or send me a message in Slack.

**Comment by Jordan-A** [comment]
@cklima616 I'm currently working on pr #77 and I could implement this fix that will be merged into master.  Just to clarify we want to remove all the main methods in the modules except the `cogitate.py` file, right?
