### ISSUE TITLE
Accidental merge into master?

### ISSUE THREAD

**Issue by noorbuchi** [GatorCogitate/cogitate_tool#81]
Hi everyone! Very recently, the command line interface branch was merged into master without getting the needed requirements in a passing build and a review from project managers and other contributors. This caused the master branch build to fail and added some changes that were not intended. I created this issue to discuss how we can go about reversing these changes, fixing some of those issues, and helping the CLI group merge their branch with the needed reviews.

**Comment by bagashvilit** [comment]
Could someone from CLI team confirm that it was an accidental merge so that we take appropriate actions to revert it?

**Comment by noorbuchi** [comment]
At the moment, I can create a pull request to revert all of the changes made by that merge. Please let us know if the change was or was not intended so we can figure out what to do from here.

**Comment by johnsc1** [comment]
I had communicated with the CLI team that the branch command-line-interface should not be merged into master until all of the features and implemented, our test suite is complete, and all Travis checks pass.

**Comment by JMilamber** [comment]
this was in fact an accidental merge

**Comment by JMilamber** [comment]
In the pull request (linked above )I had made to merge master into The Command Line Interface, there were conflicts that needed to be resolved and I attempted to do so from the github website using theri tool to update the code to use all of the code from the master branch. When i did so, if you look in the commits in the pr linked above, there is one that says it merged into master. However it states that only a single line in a file was to be changed

**Comment by noorbuchi** [comment]
@JMilamber no worries mistakes happen. I just wanted to make sure that all teams are on the same page when it comes to merging PRs and we're making sure that all changes are approved. Considering that, please make sure to approve the PR I created that would revert those changes, it is #82

**Comment by JMilamber** [comment]
will do

**Comment by noorbuchi** [comment]
Now that the merge was reverted, your team can create another PR to get it reviewed and merged when ready.

**Comment by johnsc1** [comment]
I am closing this issue since the merge was reverted.
