### ISSUE TITLE
README_documentation

### ISSUE THREAD

**Issue by bagashvilit** [GatorCogitate/cogitate_tool#85]
Hi everyone, can I trouble you all to quickly comment on this issue with suggestions for future development and limitations of our tool. It can be something like this:
`TODO:` improve code coverage
`TODO:` Automate the merging of duplicate usernames.
It's important to make the comments as soon as possible so that we have enough time to document them in `README.md`.

**Comment by noorbuchi** [comment]
Future development suggestions:
- Allow the user to choose a branch to analyze
- Include dates of commits to filter data in a timeline

These are some of the things I have in mind for now. I'll add another comment on this issue if I remember something else.

**Comment by Cory-Wiard** [comment]
Future development suggestion:

- Line graphs displaying the commits over time to see daily or weekly contribution

-  continue to refactor/change program to continue to improve efficiency and run time

**Comment by MaddyKapfhammer** [comment]
I have created a PR with these as additions to the documentation. I would appreciate it if you guys could review this PR and either approve it or request changes, so we can get it merged as soon as possible. The PR is: #86, once this is approved and merged I think that we can close this issue!

**Comment by MaddyKapfhammer** [comment]
The final documentation has been merged, so I am now going to close this issue.
