### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by hinckleyc** [GatorCogitate/cogitate_tool#9]
Should we make pull requests for our demo code?

**Comment by gkapfham** [comment]
Hi @hinckleyc, thanks for this question. My advice to the members of the team is that every week you should be making contributions to the long-term software project in the form of Python source code, configuration files, and technical documentation. As such, I suggest that the demonstrations show functionality that you could, whenever possible, imagine being integrated into the tool.

**Comment by koscinskic** [comment]
We've developed a schedule system on the project_manager_info repository (link will be provided in this repository's README) to coordinate when pull requests should be made and for what features. Having said, for this particular issue, we'll be deciding during our lab today what to do regarding the demos.
