### ISSUE TITLE
Dependencies Update Needed

### ISSUE THREAD

**Issue by noorbuchi** [GatorCogitate/cogitate_tool#91]
While @carmop and I were discussing how to run the tool, we noticed that there is a dependency missing from the `Pipfile`. This dependency is the `validators` package used by the CLI team and in the `cogitate.py` module. It is responsible for confirming that a valid GitHub URL is being sent in as an argument. When installing the dependencies using the virtual environment, this package is not being installed, considering that it is missing from the `Pipfile`, and it is causing a name error. I suggest that we create a new quick fix branch where we add the package to the `Pipfile`. Before doing that, I want to confirm that multiple people are having this issue. Please feel free to comment on this issue tracker if you've been encountering this error or any other error while running the tool.

**Comment by cklima616** [comment]
Is there a way to create this change directly to Master without messing anyone up? 
I think we had this change to the Pipfile initially, but other merges may have removed it accidentally. I'm happy to be of help! If making a separate branch is necessary, I am happy to do that and make a PR today.

**Comment by noorbuchi** [comment]
@cklima616 I think that creating a separate branch would be better simply to avoid breaking the build. Going through the review process would also be helpful to see if anyone has any additional suggestions for fixes.

**Comment by noorbuchi** [comment]
Also, I haven't been able to replicate this issue myself. This was something that @carmop told me about. So I want to confirm that this is an issue for many different users so we can know how to go about fixing it. In @carmop 's case, adding the package to the pipfile and reinstalling the dependencies fixed the issue.

**Comment by cklima616** [comment]
https://github.com/GatorCogitate/cogitate_tool/pull/92

**Comment by cklima616** [comment]
@noorbuchi I created a PR with the change! I will post it in Slack to get some reviewers and some more insight as to who has had a similar error.
